algoritmo "AULA09_01"
// Função : Repetição Enquanto
// Autor :
// Data : 06/01/2021
// Seção de Declarações
var
salto,valor,contador: inteiro
inicio
// Seção de Comandos
contador <- 0
Escreva("Quer contar até quanto? ")
Leia(valor)
Escreva("Qual será o valor do salto? ")
Leia(salto)
Enquanto (contador <= valor) faca
   Escreval(contador)
   contador <- contador + salto
FimEnquanto
Escreval("Terminei de Contar")
fimalgoritmo
