algoritmo "AULA07_01"
// Função :
// Autor :
// Data : 06/01/2021
// Seção de Declarações
var
idade,ano,nasc:inteiro
inicio
// Seção de Comandos
Escreva("Em que ano estamos? ")
Leia(ano)
Escreva("Em que ano você nasceu? ")
Leia(nasc)
idade<- ano - nasc
Escreva("Em ", ano, " você terá ", idade, " anos")
Se (idade>=21) entao
   Escreval(" e já terá atingido a maioridade")
senao
   Escreval(" e não terá atingido a maioridade")
fimse
fimalgoritmo

